name: oneid_sdk_eg
description: oneid example app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  webview_flutter: ^4.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  oneid_flutter: 
    path: ../
    # git:
    #   url: https://github.com/Joshuauzor/oneid-flutter-sdk.git
    #   ref: master

flutter:

  uses-material-design: true

  